//! Embedded Mosquitto broker, spawned and supervised by the gateway process.
//!
//! Mirrors the placenet-home model: instead of running the broker in Docker, the
//! gateway binary writes `mosquitto.conf` at runtime, bootstraps the dynamic
//! security state once, then spawns `mosquitto` as a child process. The child is
//! tied to the gateway's lifetime (`kill_on_drop` + `PR_SET_PDEATHSIG`) and
//! respawned if it exits, so a single systemd unit owns the whole stack.
//!
//! Two listeners are configured:
//!   * `mqtt_port` (default 1883) — plaintext, bound to 127.0.0.1 only. This is
//!     the gateway's dynsec admin channel; never reachable off-host.
//!   * `broker_mqtts_port` (default 8883) — public MQTTS. Hamlets connect here
//!     with the per-device credentials the gateway provisions via dynsec.

use std::process::Stdio;
use std::time::Duration;

use tokio::io::{AsyncBufReadExt, AsyncWriteExt, BufReader};
use tokio::process::{Child, Command};
use tracing::{error, info, warn};

use crate::config::GatewayConfig;

/// Path to the generated mosquitto config file (inside `config_dir`).
fn config_file(config: &GatewayConfig) -> std::path::PathBuf {
    config.config_dir.join("mosquitto.conf")
}

/// Path to the persisted dynamic-security state (inside `data_dir`).
fn dynsec_file(config: &GatewayConfig) -> std::path::PathBuf {
    config.data_dir.join("dynamic-security.json")
}

/// Write `mosquitto.conf` to `config_dir`, creating the config + data dirs.
///
/// Authentication is enforced globally by the dynamic-security plugin; with no
/// matching ACL the default is DENY, so each device only reaches its own topics.
pub async fn write_config(config: &GatewayConfig) -> Result<(), String> {
    tokio::fs::create_dir_all(&config.config_dir)
        .await
        .map_err(|e| format!("failed to create config dir: {e}"))?;
    tokio::fs::create_dir_all(&config.data_dir)
        .await
        .map_err(|e| format!("failed to create data dir: {e}"))?;

    let data_dir = config.data_dir.display();
    let contents = format!(
        "# Auto-generated by placenet-cloud-gateway. Do not edit by hand.\n\
         per_listener_settings false\n\
         allow_anonymous false\n\
         \n\
         plugin {plugin}\n\
         plugin_opt_config_file {dynsec}\n\
         \n\
         persistence true\n\
         persistence_location {data}/\n\
         log_dest stderr\n\
         \n\
         # Internal plaintext listener for the gateway's dynsec admin connection.\n\
         listener {admin_port} 127.0.0.1\n\
         \n\
         # Public MQTTS listener. cert/key options bind to the most recent listener.\n\
         listener {mqtts_port}\n\
         certfile {certfile}\n\
         keyfile {keyfile}\n\
         tls_version tlsv1.2\n",
        plugin = config.dynsec_plugin,
        dynsec = dynsec_file(config).display(),
        data = data_dir,
        admin_port = config.mqtt_port,
        mqtts_port = config.broker_mqtts_port,
        certfile = config.broker_certfile.display(),
        keyfile = config.broker_keyfile.display(),
    );

    let path = config_file(config);
    tokio::fs::write(&path, contents)
        .await
        .map_err(|e| format!("failed to write mosquitto.conf: {e}"))?;
    info!(config = %path.display(), "wrote mosquitto config");
    Ok(())
}

/// Bootstrap the dynamic-security state on first run.
///
/// `mosquitto_ctrl dynsec init` is an OFFLINE command: it only writes the JSON
/// state file (creating the admin client), it does not connect to a broker. We
/// run it only when the file is absent so the admin credential is created once
/// and then persisted in `data_dir`.
pub async fn init_dynsec(config: &GatewayConfig) -> Result<(), String> {
    let dynsec = dynsec_file(config);
    if dynsec.exists() {
        info!(file = %dynsec.display(), "dynsec state already present, skipping init");
        return Ok(());
    }

    info!(admin = %config.dynsec_admin_user, "initialising dynsec admin");
    let mut child = Command::new(&config.mosquitto_ctrl_binary)
        .arg("dynsec")
        .arg("init")
        .arg(&dynsec)
        .arg(&config.dynsec_admin_user)
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|e| format!("failed to run mosquitto_ctrl: {e}"))?;

    // Feed the password twice in case the prompt asks for confirmation.
    if let Some(mut stdin) = child.stdin.take() {
        let line = format!("{}\n{}\n", config.dynsec_admin_password, config.dynsec_admin_password);
        stdin
            .write_all(line.as_bytes())
            .await
            .map_err(|e| format!("failed to write dynsec admin password: {e}"))?;
        drop(stdin);
    }

    let output = child
        .wait_with_output()
        .await
        .map_err(|e| format!("failed to wait for mosquitto_ctrl: {e}"))?;
    if !output.status.success() {
        return Err(format!(
            "mosquitto_ctrl dynsec init failed: {}",
            String::from_utf8_lossy(&output.stderr)
        ));
    }
    info!("dynsec initialised");
    Ok(())
}

/// Spawn a single `mosquitto` child process bound to the gateway's lifetime.
fn spawn_mosquitto(config: &GatewayConfig) -> Result<Child, String> {
    let cfg = config_file(config);
    let mut cmd = Command::new(&config.mosquitto_binary);
    cmd.args(["-c", &cfg.to_string_lossy()])
        .stdout(Stdio::null())
        .stderr(Stdio::piped())
        .kill_on_drop(true);

    // Linux: have the kernel send SIGTERM to mosquitto if the gateway dies, so
    // the broker can never outlive its supervisor.
    #[cfg(target_os = "linux")]
    unsafe {
        cmd.pre_exec(|| {
            libc::prctl(libc::PR_SET_PDEATHSIG, libc::SIGTERM as libc::c_ulong, 0, 0, 0);
            Ok(())
        });
    }

    let mut child = cmd
        .spawn()
        .map_err(|e| format!("failed to spawn mosquitto: {e}"))?;

    if let Some(stderr) = child.stderr.take() {
        let reader = BufReader::new(stderr);
        tokio::spawn(async move {
            let mut lines = reader.lines();
            while let Ok(Some(line)) = lines.next_line().await {
                info!(target: "mosquitto", "{}", line);
            }
        });
    }

    Ok(child)
}

/// Prepare config + dynsec state, then start a supervisor task that keeps a
/// `mosquitto` child running, respawning it (with a short backoff) if it exits.
/// The child is dropped — and thus killed — when the process shuts down.
pub async fn start_supervised(config: &GatewayConfig) -> Result<(), String> {
    write_config(config).await?;
    init_dynsec(config).await?;

    let config = config.clone();
    tokio::spawn(async move {
        loop {
            let mut child = match spawn_mosquitto(&config) {
                Ok(c) => {
                    info!(pid = child_pid(&c), "mosquitto started");
                    c
                }
                Err(e) => {
                    error!("{e}");
                    tokio::time::sleep(Duration::from_secs(5)).await;
                    continue;
                }
            };

            match child.wait().await {
                Ok(status) => warn!("mosquitto exited with status {status}; respawning"),
                Err(e) => error!("error waiting for mosquitto: {e}; respawning"),
            }
            tokio::time::sleep(Duration::from_secs(2)).await;
        }
    });

    Ok(())
}

fn child_pid(child: &Child) -> u32 {
    child.id().unwrap_or(0)
}
